# Generated by Django 4.2.5 on 2023-10-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
