# Generated by Django 4.2.5 on 2023-10-09 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_audiofile_audio_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='broadcast',
            new_name='title',
        ),
        migrations.AddField(
            model_name='broadcast',
            name='cover',
            field=models.FileField(blank=True, null=True, upload_to='images/'),
        ),
    ]
