# Generated by Django 4.2.5 on 2023-10-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_rename_broadcast_audiofile_title_broadcast_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiofile',
            name='name',
            field=models.CharField(default='', max_length=300),
        ),
    ]
