# Generated by Django 4.2.5 on 2023-10-09 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_audiofile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='audiofile',
            old_name='name',
            new_name='audio_name',
        ),
        migrations.RenameField(
            model_name='audiofile',
            old_name='title',
            new_name='broadcast',
        ),
    ]
