# Generated by Django 4.2.5 on 2023-10-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_uploadsong_uploadsong_audio_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiofile',
            name='desc',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
